version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: "start-notebook.sh --ServerApp.root_dir=/home/jovyan/work --ServerApp.token=''"
    user: root
